apiVersion: v1
kind: Service
metadata:
  labels:
    app: temp-demo-dmz
    apic-managed: "true"
  creationTimestamp: null
  name: temp-demo-dmz
  namespace: apic-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: temp-demo-dmz
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: temp-demo-dmz
  name: temp-demo-dmz
  namespace: apic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: temp-demo-dmz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: temp-demo-dmz
        run: temp-demo-dmz
    spec:
      containers:
      - image: jocotech/apib-demo
        imagePullPolicy: Always
        name: temp-demo-dmz
        ports:
        - containerPort: 8080
          name: http
        resources: {}
status: {}
