apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    apic-managed: "true"
  creationTimestamp: null
  name: user
  namespace: apic-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: user
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
  namespace: apic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
        run: user
    spec:
      containers:
      - image: jocotech/user:2
        imagePullPolicy: Always
        name: user
        ports:
        - containerPort: 8080
          name: http
        resources: {}
status: {}
